
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec  5 2025 14:21:36 IST (Dec  5 2025 08:51:36 UTC)

// Verification Directory fv/APN_ANF 

module APN_ANF(a, b);
  input [3:0] a;
  output [3:0] b;
  wire [3:0] a;
  wire [3:0] b;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_23;
  OAI22M1S g384(.A1 (a[1]), .A2 (n_13), .B1 (n_14), .B2 (n_2), .Z
       (b[3]));
  AO21M1SA g383(.A1 (n_10), .A2 (a[2]), .B (n_11), .Z (b[1]));
  AO211M1SA g382(.A1 (n_8), .A2 (a[1]), .B (n_9), .C (n_23), .Z (b[2]));
  OAI221M1S g381(.A1 (a[1]), .A2 (n_4), .B1 (n_14), .B2 (n_3), .C
       (n_12), .Z (b[0]));
  AN2M2S g387(.A (n_12), .B (n_6), .Z (n_13));
  OAI33M1S g386(.A1 (a[1]), .A2 (a[2]), .A3 (n_10), .B1 (a[3]), .B2
       (a[0]), .B3 (n_14), .Z (n_11));
  NR2M1S g392(.A (a[1]), .B (n_10), .Z (n_9));
  NR2B1M1S g388(.B (a[2]), .NA (n_10), .Z (n_8));
  ND2M1S g389(.A (n_23), .B (n_5), .Z (n_12));
  OAI21B20M1S g391(.B (a[3]), .NA1 (a[2]), .NA2 (n_5), .Z (n_6));
  ND2M1S g385(.A (n_3), .B (a[3]), .Z (n_4));
  AOI21M1S g390(.A1 (a[2]), .A2 (a[0]), .B (n_3), .Z (n_2));
  ND2M1S g395(.A (n_0), .B (a[0]), .Z (n_10));
  NR2M1S g393(.A (a[0]), .B (a[2]), .Z (n_3));
  CKINVM1S g399(.A (a[1]), .Z (n_14));
  CKINVM1S g396(.A (a[3]), .Z (n_0));
  CKINVM1S g397(.A (a[0]), .Z (n_5));
  NR2B1M1S g2(.B (a[3]), .NA (a[2]), .Z (n_23));
endmodule

