
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec  6 2025 05:30:59 IST (Dec  6 2025 00:00:59 UTC)

// Verification Directory fv/APN_ANF 

module APN_ANF(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_12, n_13, n_15, n_23;
  OAI221M1S g374(.A1 (n_9), .A2 (n_12), .B1 (n_8), .B2 (n_13), .C
       (n_3), .Z (out[3]));
  OAI221M1S g373(.A1 (n_0), .A2 (n_5), .B1 (in[3]), .B2 (n_4), .C
       (n_15), .Z (out[2]));
  OAI211M1S g372(.A1 (in[2]), .A2 (n_15), .B (n_7), .C (n_10), .Z
       (out[1]));
  AO222M1SA g375(.A1 (n_13), .A2 (in[1]), .B1 (n_2), .B2 (n_23), .C1
       (n_6), .C2 (in[2]), .Z (out[0]));
  AOI21M1S g379(.A1 (in[2]), .A2 (in[1]), .B (n_23), .Z (n_12));
  OAI21M1S g380(.A1 (in[3]), .A2 (n_9), .B (in[2]), .Z (n_10));
  ND2M1S g378(.A (n_8), .B (in[0]), .Z (n_15));
  ND2M1S g377(.A (n_6), .B (in[1]), .Z (n_7));
  AOI21M1S g381(.A1 (n_4), .A2 (in[3]), .B (n_6), .Z (n_5));
  ND3M1S g376(.A (n_8), .B (in[2]), .C (n_9), .Z (n_3));
  CKINVM1S g382(.A (n_2), .Z (n_13));
  NR2M1S g384(.A (in[0]), .B (in[2]), .Z (n_2));
  NR2M1S g383(.A (in[0]), .B (in[3]), .Z (n_6));
  NR2M1S g386(.A (in[1]), .B (in[3]), .Z (n_8));
  CKINVM1S g390(.A (in[2]), .Z (n_4));
  CKINVM1S g389(.A (in[1]), .Z (n_0));
  CKINVM1S g388(.A (in[0]), .Z (n_9));
  NR2B1M1S g2(.B (in[1]), .NA (in[3]), .Z (n_23));
endmodule

