
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec  6 2025 05:38:14 IST (Dec  6 2025 00:08:14 UTC)

// Verification Directory fv/APN_ANF 

module APN_ANF(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_19;
  OAI22M1S g384(.A1 (in[1]), .A2 (n_13), .B1 (n_14), .B2 (n_2), .Z
       (out[3]));
  AO21M1SA g383(.A1 (n_10), .A2 (in[2]), .B (n_11), .Z (out[1]));
  AO211M1SA g382(.A1 (n_8), .A2 (in[1]), .B (n_9), .C (n_19), .Z
       (out[2]));
  OAI221M1S g381(.A1 (in[1]), .A2 (n_4), .B1 (n_14), .B2 (n_3), .C
       (n_12), .Z (out[0]));
  AN2M2S g387(.A (n_12), .B (n_6), .Z (n_13));
  OAI33M1S g386(.A1 (in[1]), .A2 (in[2]), .A3 (n_10), .B1 (in[3]), .B2
       (in[0]), .B3 (n_14), .Z (n_11));
  NR2M1S g392(.A (in[1]), .B (n_10), .Z (n_9));
  NR2B1M1S g388(.B (in[2]), .NA (n_10), .Z (n_8));
  ND2M1S g389(.A (n_19), .B (n_5), .Z (n_12));
  OAI21B20M1S g391(.B (in[3]), .NA1 (in[2]), .NA2 (n_5), .Z (n_6));
  ND2M1S g385(.A (n_3), .B (in[3]), .Z (n_4));
  AOI21M1S g390(.A1 (in[2]), .A2 (in[0]), .B (n_3), .Z (n_2));
  ND2M1S g395(.A (n_0), .B (in[0]), .Z (n_10));
  NR2M1S g393(.A (in[0]), .B (in[2]), .Z (n_3));
  CKINVM1S g399(.A (in[1]), .Z (n_14));
  CKINVM1S g396(.A (in[3]), .Z (n_0));
  CKINVM1S g397(.A (in[0]), .Z (n_5));
  NR2B1M1S g2(.B (in[3]), .NA (in[2]), .Z (n_19));
endmodule

